Repository saltyfacu/ape-tax, pull requests merged in 2021-09, with the labels that each got.

#97 BugFix/Fixing deposits buttons + ui update
  components/Navbar.js
  pages/[slug]/index.js
Labels: enhancement

#100 Feature/ApeApi
  package.json
  pages/api/vaults.js
  utils/fn.js
  utils/yVault.abi.json
  yarn.lock
Labels: enhancement

#104 Feature/api doc
  README.md
  utils/fn.js
Labels: Documentation 📜

#107 Dependencies/Fix Inquirer
  package.json
  yarn.lock
Labels: Bug 🐞

#108 BugFix/Allow depositAll
  pages/[slug]/index.js
Labels: Bug 🐞

#111 BugFix/DepositLimit 0
  pages/[slug]/index.js
Labels: Bug 🐞

#106 feat: add fantom tarrot vault
  utils/vaults.json
Labels: Feature 🚀

#110 Feature/API custom rpc
  README.md
  pages/api/vaults.js
Labels: Improvement 🦄

#114 Feature/Fantom RPC use
  contexts/useWeb3.js
  next.config.js
  pages/[slug]/index.js
  utils/API.js
Labels: Improvement 🦄

#118 Feature/API get one vault APY
  pages/api/specificApy.js
Labels: Improvement 🦄

#128 Feature/ZapVault address
  utils/vaults.json
Labels: Improvement 🦄

#132 Feature/Matic, API and strategies
  contexts/useWeb3.js
  next.config.js
  pages/[slug]/index.js
  pages/api/specificApy.js
  pages/api/tvl.js
  pages/api/vaults.js
  tailwind.config.js
  utils/ABI/erc20.abi.json
  utils/ABI/yVault.abi.json
Labels: Bug 🐞, Improvement 🦄

#134 Feature/Introducing Arbitrum Support
  README.md
  contexts/useWeb3.js
  next.config.js
  pages/[slug]/index.js
  pages/api/specificApy.js
  pages/api/tvl.js
  pages/api/vaults.js
  scripts/newVault.js
  utils/API.js
  utils/chains.json
  utils/vaults.json
Labels: Improvement 🦄
